-- AUTO-GENERATED: MIGRAIÓN 50 TABLAS CORE (SUPABASE)
-- Basado en ESTRUCTURA_WEB_50_TABLAS_CORE.md

CREATE TABLE IF NOT EXISTS public."Pacientes" (
  "IdPac" integer,
  "IdCli" integer,
  "IdCliPac" integer,
  "NumPac" text,
  "IdMutDefec" integer,
  "IdCliDefec" integer,
  "Nombre" text,
  "Apellidos" text,
  "NIF" text,
  "Direccion" text,
  "IdPoblacio" integer,
  "CP" text,
  "Tel1" text,
  "Tel2" text,
  "TelMovil" text,
  "Fax" text,
  "Email" text,
  "Web" text,
  "FecNacim" timestamp with time zone,
  "Comodin1" text,
  "Comodin2" text,
  "Comodin3" text,
  "Comodin4" text,
  "Comodin5" text,
  "Comodin6" text,
  "IdRefOri" integer,
  "RefOriTxt" text,
  "IdRefDes" integer,
  "Descuento" integer,
  "IdProfesio" integer,
  "IdEcivil" integer,
  "NumHijos" integer,
  "Sexo" text,
  "IdTrato" integer,
  "Foto" integer,
  "IdEstado" integer,
  "Mailing" boolean,
  "Notas" text,
  "FecAlta" timestamp with time zone,
  "TipoOdg" integer,
  "AceptaLOPD" boolean,
  "AceptaInfo" boolean,
  "AceptaSMS" boolean,
  "IdCol" integer,
  "IdColAux" integer,
  "AgNumVis" integer,
  "AgTpoTotE" integer,
  "AgTpoTotR" integer,
  "AgTpoTotAt" integer,
  "_fechareg" timestamp with time zone,
  "IdProced" integer,
  "CIP" text,
  "AgNumFallos" integer,
  "Comodin7" text,
  "IdIdioma" integer,
  "GrupoSanguineo" text,
  "IdCentro" integer,
  "TipoDocIdent" integer,
  "NumSS" text,
  "Exitus" timestamp with time zone,
  "ExitusObs" text,
  "Inactivo" timestamp with time zone,
  "MotivoInactivo" text,
  "IdPacReferidor" integer,
  "AceptaEmail" boolean,
  "AceptaPostal" boolean,
  "IdPaisIdent" integer,
  "IdCliTutor" integer,
  "_version" integer,
  "_fechaModif" timestamp with time zone,
  "_idUserModif" integer,
  "LecturaDocIdentEstado" integer,
  "LecturaDocIdentFecha" timestamp with time zone,
  "LecturaDocIdentIdUser" integer,
  "IdUserAsesor" integer,
  "AceptaGDPR" boolean,
  "IdTipoDireccion" integer,
  "SeccionCensal" text,
  "CoordenadasX" text,
  "CoordenadasY" text,
  "NoContactable" boolean,
  "Derivado" boolean,
  "ExternalId" uuid,
  "Guid_Tenant" uuid,
  "AceptaBots" boolean,
  "AceptaWhatsApp" boolean,
  PRIMARY KEY ("IdPac")
);

CREATE TABLE IF NOT EXISTS public."TtosMed" (
  "IdPac" integer,
  "NumTto" integer,
  "IdTto" integer,
  "ZonasBoca" integer,
  "PiezasAdu" numeric,
  "PiezasLec" numeric,
  "PiezasNum" numeric,
  "ZonasPieza" numeric,
  "DespX" integer,
  "DespY" integer,
  "Rotacion" integer,
  "StaTto" integer,
  "FecIni" timestamp with time zone,
  "FecFin" timestamp with time zone,
  "IdCol" integer,
  "Notas" text,
  "Importe" numeric,
  "Dto" integer,
  "Pendiente" numeric,
  "IdTipoOdg" integer,
  "Actos" integer,
  "Tiempo" integer,
  "IdCli" integer,
  "Ident" integer,
  "Autoriz" text,
  "NumFinan" text,
  "IdUser" integer,
  "Comodin1" text,
  "IdColAux" integer,
  "Edu10" integer,
  "Edu11" integer,
  "Edu12" integer,
  "Edu13" integer,
  "Edu14" integer,
  "Edu20" integer,
  "Edu21" integer,
  "Edu22" integer,
  "Edu23" integer,
  "Edu24" integer,
  "TipoOperac" integer,
  "CampoAux1" text,
  "CampoAux2" text,
  "CampoAux3" text,
  "CampoAux4" text,
  "CampoAux5" text,
  "CampoAux6" text,
  "SesRealiz" integer,
  "FechaCaduc" timestamp with time zone,
  "_fechareg" timestamp with time zone,
  "IdRef" integer,
  "IdProced" integer,
  "IdTipoEspec" integer,
  "NumDocUnico" text,
  "IdCentro" integer,
  "IdEmisor" integer,
  "ImporteDto" numeric,
  "IdColValida" integer,
  "FechaValida" timestamp with time zone,
  "UniqueID" integer,
  "_version" integer,
  "IdPresuTto" integer,
  "DescTarifaConector" text,
  "ImportePrivado" numeric,
  "ImporteMutua" numeric,
  "IdUserEdit" integer,
  "_fecharegEdit" timestamp with time zone,
  "NFacturaEl" text,
  "NumTransaccion" integer,
  "IdDevolucionTransaccion" integer,
  "IdPlanEcoCuota" integer,
  "IdCCDiagnostico" integer,
  "Cuadrantes" numeric,
  "Arcadas" numeric,
  "FecExpoCp" timestamp with time zone,
  "Guid_Tenant" uuid,
  "CId" text,
  PRIMARY KEY ("Ident")
);

CREATE TABLE IF NOT EXISTS public."DCitas" (
  "IdUsu" integer,
  "IdOrden" integer,
  "Fecha" integer,
  "Hora" integer,
  "Duracion" integer,
  "IdSitC" integer,
  "Texto" text,
  "FlgBloqueo" text,
  "Contacto" text,
  "Movil" text,
  "IdPac" integer,
  "HorLlegada" integer,
  "Retraso" integer,
  "BOX" text,
  "HorConsul" integer,
  "HorFinal" integer,
  "NOTAS" text,
  "NUMPAC" text,
  "AgStats" text,
  "FecAlta" timestamp with time zone,
  "Recordada" integer,
  "Confirmada" integer,
  "IdBox" integer,
  "IdCitasP" integer,
  "NumOcur" integer,
  "DCitasGrp" text,
  "CantIntegGrp" integer,
  "Gratuita" boolean,
  "IdUserIns" integer,
  "IdCli" integer,
  "MotivoAnulacion" text,
  "NumAuto" text,
  "IdRef" integer,
  "IdProced" integer,
  "IdPartner" integer,
  "FecNacim" timestamp with time zone,
  "NIF" text,
  "IdPacExt" text,
  "IdOpc" text,
  "Email" text,
  "IdCita" integer,
  "IdCia" integer,
  "IdTipoEspec" integer,
  "IdCol" integer,
  "IdCentro" integer,
  "Comodin1" text,
  "Comodin2" text,
  "Aceptada" timestamp with time zone,
  "IdCitaConector" text,
  "HorSitCita" timestamp with time zone,
  "IdGrAgdOpc" integer,
  "IdMotivoAnulacion" integer,
  "IdIcono" integer,
  "NumActos1Tto" integer,
  "IdTarifa" integer,
  "OrigenExt" text,
  "SolicitanteNUMPAC" text,
  "SolicitanteDesc" text,
  "TipoDocIdent" integer,
  "IdPaisIdent" integer,
  "Id_MotivoCitacion" integer,
  "IdOrigenIns" integer,
  "IdOrden_Bloqueado" integer,
  "EnviarRecordatorio" timestamp with time zone,
  "EnviarConfirmacion" timestamp with time zone,
  "OrigenAnulacion" integer,
  "AnulacionGestionada" timestamp with time zone,
  PRIMARY KEY ("IdUsu", "IdOrden")
);

CREATE TABLE IF NOT EXISTS public."Clientes" (
  "IdCli" integer,
  "TipoCli" text,
  "Nombre" text,
  "Apellidos" text,
  "Direccion" text,
  "IdPoblacio" integer,
  "CP" text,
  "NIF" text,
  "Antecedent" text,
  "Tel1" text,
  "Tel2" text,
  "TelMovil" text,
  "Fax" text,
  "Email" text,
  "Web" text,
  "Comodin1" text,
  "Comodin2" text,
  "IdTrato" integer,
  "Cuenta" text,
  "Mailing" boolean,
  "Notas" text,
  "Entidad" text,
  "Oficina" text,
  "DC" text,
  "IdBanco" integer,
  "FecAlta" timestamp with time zone,
  "SISTEMA" text,
  "TARIFA" text,
  "FecTarifa" timestamp with time zone,
  "Inactivo" text,
  "FecBaja" timestamp with time zone,
  "CodCli" text,
  "_fechareg" timestamp with time zone,
  "IdEmisor" integer,
  "IdCIA" integer,
  "IdAuxPTarj" integer,
  "DiaFact" integer,
  "Modelo" integer,
  "ModoFact" integer,
  "OrdenFactura" integer,
  "DesglosarModalidad" text,
  "RazonSocial" text,
  "DiasCaducidad" integer,
  "SCCodSCta" text,
  "SCCodDept" text,
  "SCCodProd" text,
  "SCCodProy" text,
  "SCCodSCtaANT" text,
  "DiaFactTalon" integer,
  "IdCentro" integer,
  "TipoDocIdent" integer,
  "CodIBAN" text,
  "CodTar" integer,
  "CodImgRC" text,
  "IdIdioma" integer,
  "FecNacim" timestamp with time zone,
  "TipoEntidad" integer,
  "IdentPS" text,
  "IdPaisIdent" integer,
  "LecturaDocIdentEstado" integer,
  "LecturaDocIdentFecha" timestamp with time zone,
  "LecturaDocIdentIdUser" integer,
  "ExternalId" uuid,
  "Id_TipoCliente" integer,
  "_version" integer,
  "_idUserReg" integer,
  "_fechaModif" timestamp with time zone,
  "_idUserModif" integer,
  "Guid_Tenant" uuid,
  PRIMARY KEY ("IdCli")
);

CREATE TABLE IF NOT EXISTS public."TColabos" (
  "IdCol" integer,
  "Codigo" text,
  "Alias" text,
  "Apellidos" text,
  "Nombre" text,
  "IdPoblacio" integer,
  "CP" text,
  "Direccion" text,
  "NIF" text,
  "Tel1" text,
  "Tel2" text,
  "TelMovil" text,
  "Fax" text,
  "EMail" text,
  "Web" text,
  "FecBaja" timestamp with time zone,
  "Activo" text,
  "Horario" text,
  "Notas" text,
  "Comision" integer,
  "ReComision" text,
  "Cobro" text,
  "CodInt" text,
  "FecAlta" timestamp with time zone,
  "ReGastos" text,
  "TpcGastos" integer,
  "Gasto" text,
  "PrecioFijo" text,
  "TpcPFijo" integer,
  "IdTipoColab" integer,
  "NumColeg" text,
  "CobPropios" text,
  "TipoRealizado" text,
  "IdGrpColab" integer,
  "IRPF" integer,
  "TipoComision" text,
  "JefeGrupo" integer,
  "IdColJefeGrupo" integer,
  "IdRef" integer,
  "IdProced" integer,
  "IdEmisor" integer,
  "PIN" text,
  "FechaPIN" timestamp with time zone,
  "InicioEspecCM" timestamp with time zone,
  "TipoContrato" integer,
  "TipoDocIdent" integer,
  "IdPaisIdent" integer,
  "ExternalId" uuid,
  "ExternalLogin" text,
  "ExternalPwd" text,
  "Guid_Tenant" uuid,
  PRIMARY KEY ("IdCol")
);

CREATE TABLE IF NOT EXISTS public."PagoCli" (
  "IdPagoCli" integer,
  "IdCli" integer,
  "Pagado" numeric,
  "FecPago" timestamp with time zone,
  "IdForPago" integer,
  "Oficina" text,
  "Entidad" text,
  "NumIngre" text,
  "IdBanco" integer,
  "IdUser" integer,
  "Docs" text,
  "NRecibo" text,
  "NCPago" text,
  "FecExpoCP" timestamp with time zone,
  "IdAnulado" integer,
  "_fechareg" timestamp with time zone,
  "ContabSC" text,
  "IdCentro" integer,
  "CodIBAN" text,
  "IdMotivo" integer,
  "NoDisponible" timestamp with time zone,
  "Cuotas" integer,
  "FechaCuota" timestamp with time zone,
  "IdentTM" integer,
  "NFactura" text,
  "Tipo" integer,
  "IdentPS" integer,
  "FP_Codigo1" text,
  "FP_Codigo2" text,
  "FP_Codigo3" text,
  "IdLiqComisionDet" integer,
  "Automatico" boolean,
  "NumTransaccion" integer,
  "IdDevolucionTransaccion" integer,
  "IdPasarelaPago" integer,
  "IdRemesaBancaria" integer,
  "IdPlanEcoCuota" integer,
  "IdPagoCliRelacionado" integer,
  "FechaImport" timestamp with time zone,
  "CId" text,
  "Id_SolicitudDevolucion" integer,
  "Guid_Tenant" uuid,
  PRIMARY KEY ("IdPagoCli")
);

CREATE TABLE IF NOT EXISTS public."HL7PacientesIN" (
  "Id" integer,
  "IdMsgHL7" text,
  "TipoMsgHL7" text,
  "NombreAppEnvia" text,
  "MsgHL7" text,
  "_fechareg" timestamp with time zone,
  "IdPac" integer,
  "LogPac" text,
  "PID_1" text,
  "PID_2_1" text,
  "PID_3_1" text,
  "PID_3_2" text,
  "PID_3_3" text,
  "PID_3_4" text,
  "PID_4_1" text,
  "PID_4_2" text,
  "PID_4_3" text,
  "PID_4_4" text,
  "PID_5_1" text,
  "PID_5_2" text,
  "PID_5_3" text,
  "PID_5_4" text,
  "PID_6_1" text,
  "PID_6_2" text,
  "PID_6_3" text,
  "PID_6_4" text,
  "PID_7_1" text,
  "PID_8" text,
  "PID_9_1" text,
  "PID_10_1" text,
  "PID_11_1" text,
  "PID_11_2" text,
  "PID_11_3" text,
  "PID_11_4" text,
  "PID_11_5" text,
  "PID_11_6" text,
  "PID_11_7" text,
  "PID_11_8" text,
  "PID_12" text,
  "PID_13_1" text,
  "PID_13_2" text,
  "PID_13_3" text,
  "PID_13_4" text,
  "PID_13_5" text,
  "PID_13_6" text,
  "PID_13_7" text,
  "PID_14_1" text,
  "PID_15_1" text,
  "PID_16_1" text,
  "PID_17_1" text,
  "PID_18_1" text,
  "PID_19" text,
  PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Centros" (
  "IdCentro" integer,
  "CodCentro" text,
  "Descripcio" text,
  "Direccion" text,
  "IdPoblacio" integer,
  "CP" text,
  "Tel1" text,
  "Tel2" text,
  "Fax" text,
  "Email" text,
  "Web" text,
  "CIF" text,
  "Fecha_Corte" timestamp with time zone,
  "CodSerie" text,
  "ExpConta" integer,
  "Delegacion" text,
  "DescCorta" text,
  "Comodin1" text,
  "Comodin2" text,
  "Comodin3" text,
  "Comodin4" text,
  "Comodin5" text,
  "Comodin6" text,
  "RutaFichMutuas" text,
  "IdClasificacionCentro" integer,
  "CodigoEmpresaPedidos" text,
  "RutFichPedidos" text,
  "_version" integer,
  "_fechaReg" timestamp with time zone,
  "_idUserReg" integer,
  "_fechaModif" timestamp with time zone,
  "_idUserModif" integer,
  "AOAgdGUID" text,
  "ActivacionLiqTrabajosProtesis" timestamp with time zone,
  "Guid" uuid,
  "TipoDocIdent" integer,
  "Id_GDPRProfile" integer,
  "Id_UserDirector" integer,
  "Gestionable" integer,
  "Guid_Tenant" uuid,
  PRIMARY KEY ("IdCentro")
);

CREATE TABLE IF NOT EXISTS public."TUsers" (
  "IdUser" integer,
  "Login" text,
  "Pass" text,
  "Nombre" text,
  "Apellidos" text,
  "NIF" text,
  "Email" text,
  "Telef" text,
  "UsrRido" text,
  "DirRptExp" text,
  "RptGeneral" boolean,
  "FecPass" timestamp with time zone,
  "IdPerfil" integer,
  "OcultarPac" boolean,
  "OcultarPa2" boolean,
  "IdCol" integer,
  "FecDActiva" timestamp with time zone,
  "FecHActiva" timestamp with time zone,
  "UsrBloq" boolean,
  "IdTipoEspec" integer,
  "IdEmisor" integer,
  "IdGrupo" integer,
  "AdmGrupo" text,
  "_fechareg" timestamp with time zone,
  "CodInt" text,
  "PendienteResetear" boolean,
  "Guid" uuid,
  "TipoDocIdent" integer,
  "IdPaisIdent" integer,
  "Password" text,
  "Guid_DefaultCenter" uuid,
  "Custom" boolean,
  "Guid_ExternalUserDomain" uuid,
  "Guid_Tenant" uuid,
  "BannerDentIANoMostrar" timestamp with time zone,
  PRIMARY KEY ("IdUser")
);

CREATE TABLE IF NOT EXISTS public."PacientesPublic" (
  "IdPac" integer,
  "FecCreacion" timestamp with time zone,
  "FecModificacion" timestamp with time zone,
  "Direccion" text,
  "CP" text,
  "Poblacion" text,
  "Provincia" text,
  "Tel1" text,
  "Tel2" text,
  "TelMovil" text,
  "Fax" text,
  "Email" text,
  "FecNacim" timestamp with time zone,
  "Sexo" text,
  "EstadoCivil" text,
  "Profesion" text,
  "NumHijos" integer,
  "NIF" text,
  "RefOriTxt" text,
  "Nombre" text,
  "Apellidos" text,
  "Mailing" boolean,
  "AceptaLOPD" boolean,
  "AceptaInfo" boolean,
  "AceptaSMS" boolean,
  "Comodin1" text,
  "Comodin2" text,
  "Comodin3" text,
  "Comodin4" text,
  "Comodin5" text,
  "Comodin6" text,
  "Comodin7" text,
  "AceptaEmail" boolean,
  "AceptaPostal" boolean,
  "AceptaGDPR" boolean,
  PRIMARY KEY ("IdPac")
);

CREATE TABLE IF NOT EXISTS public."PasarelaPagoDet" (
  "Id" integer,
  "IdPasarelaPago" integer,
  "Tipo" integer,
  "fechaOperacion" text,
  "horaOperacion" text,
  "CodigoRespuesta" text,
  "GlosaRespuesta" text,
  "NumeroUnicoTransaccion" text,
  "Monto" numeric,
  "MontoVuelto" numeric,
  "CodigoMoneda" text,
  "MontoPropina" numeric,
  "codigoAutorizacion" text,
  "transaccionPremiada" boolean,
  "marcaTarjeta" text,
  "cuatroUltimosDigitosTarjeta" text,
  "seisPrimerosDigitosTarjeta" text,
  "tipoCuotas" text,
  "montoCuota" numeric,
  "numeroDeCuotas" text,
  "tasaAplicadaCuotas" text,
  "numeroDeOperacion" text,
  "nombreArchivoVoucher" text,
  "pathArchivoVoucher" text,
  "TipoTarjeta" text,
  "flagTipoVoucher" text,
  "MensajeRespuesta" text,
  "Voucher" text,
  "VoucherDuplicado" text,
  "_version" integer,
  "_fechaReg" timestamp with time zone,
  "_idUserReg" integer,
  "_fechaModif" timestamp with time zone,
  "_idUserModif" integer,
  "FechaImpresion" timestamp with time zone,
  PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."ExplPerio" (
  "IdPac" integer,
  "IdExplPer" integer,
  "NDent" integer,
  "borsa1" integer,
  "borsa2" integer,
  "borsa3" integer,
  "borsa4" integer,
  "borsa5" integer,
  "borsa6" integer,
  "recessio1" integer,
  "recessio2" integer,
  "recessio3" integer,
  "recessio4" integer,
  "recessio5" integer,
  "recessio6" integer,
  "sangrat1" text,
  "sangrat2" text,
  "sangrat3" text,
  "sangrat4" text,
  "placa1" text,
  "placa2" text,
  "placa3" text,
  "placa4" text,
  "movilitat1" integer,
  "movilitat2" text,
  "Id" integer,
  "_version" integer,
  "_fechaReg" timestamp with time zone,
  "_idUserReg" integer,
  "_fechaModif" timestamp with time zone,
  "_idUserModif" integer,
  "Id_PacPerio" integer,
  "Guid_Tenant" uuid,
  PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."DCitasPeriod" (
  "IdCitasP" integer,
  "IdUsu" integer,
  "IdOpc" text,
  "FechaInicio" timestamp with time zone,
  "FechaFinal" timestamp with time zone,
  "Inactiva" boolean,
  "Hora" integer,
  "Duracion" integer,
  "Texto" text,
  "Contacto" text,
  "Movil" text,
  "IdPac" integer,
  "IdBox" integer,
  "Box" text,
  "Notas" text,
  "NumPac" text,
  "FecAlta" timestamp with time zone,
  "Frecuencia" integer,
  "Periodicidad" integer,
  "DiaSem" text,
  "DiaMes" integer,
  "Mes" integer,
  "DCitasGrp" text,
  "CantIntegGrp" integer,
  "NumeroCitas" integer,
  PRIMARY KEY ("IdCitasP")
);

CREATE TABLE IF NOT EXISTS public."Pacientes_Tarifas" (
  "IdPacienteTarifa" integer,
  "IdPac" integer,
  "IdTarifa" integer,
  "Poliza" text,
  "Tarjeta" text,
  "FecAlta" timestamp with time zone,
  "FecCaduc" timestamp with time zone,
  "FecUltPase" timestamp with time zone,
  "Texto" text,
  "Version_TS" text,
  "Tarjeta24" text,
  "Certificado" integer,
  "NOrden" integer,
  "MotivoAsignacion" text,
  "IdProdModTarifa" integer,
  "IdUser" integer,
  "Comodin1" integer,
  "Comodin2" text,
  "Inactivo" timestamp with time zone,
  "_fechareg" timestamp with time zone,
  "_version" integer,
  "Localizador" text,
  "FechaLocalizador" timestamp with time zone,
  "Pista1" text,
  "Pista2" text,
  "Cobertura" text,
  "Guid_Tenant" uuid,
  PRIMARY KEY ("IdPacienteTarifa")
);

CREATE TABLE IF NOT EXISTS public."RecetasCab" (
  "IdPac" integer,
  "IdUsu" integer,
  "IdTipoEspec" integer,
  "Fecha" timestamp with time zone,
  "Descripcio" text,
  "FecIns" timestamp with time zone,
  "IdEmisor" integer,
  "IdCol" integer,
  "Publico" text,
  "FechaImpresion" timestamp with time zone,
  "Notas" text,
  "IdCentro" integer,
  "IdVisita" integer,
  "IdTalonRecetaCVE" integer,
  "NotasFarmaceutico" text,
  "Diagnostico" text,
  "TipoReceta" integer,
  "IdRecetaIdent" integer,
  "CVE" text,
  "Dispensada" timestamp with time zone,
  "NumImpresiones" integer,
  "Anulada" timestamp with time zone,
  "Guid_Tenant" uuid,
  PRIMARY KEY ("IdRecetaIdent")
);

CREATE TABLE IF NOT EXISTS public."Bancos" (
  "IdBanco" integer,
  "Descripcio" text,
  "IdPoblacio" integer,
  "CP" text,
  "Direccion" text,
  "Tel1" text,
  "Tel2" text,
  "TelMovil" text,
  "Fax" text,
  "Email" text,
  "Web" text,
  "Notas" text,
  "Entidad" text,
  "Oficina" text,
  "DC" text,
  "Cuenta" text,
  "Clinica" boolean,
  "SCCodSCta" text,
  "SCCodDept" text,
  "SCCodProd" text,
  "SCCodProy" text,
  "IdCentro" integer,
  "CodIBAN" text,
  "CodBIC" text,
  "Guid_Tenant" uuid,
  PRIMARY KEY ("IdBanco")
);

CREATE TABLE IF NOT EXISTS public."HL7Citas" (
  "IdMsg" integer,
  "Tipo" integer,
  "IdCentro" integer,
  "IdUsu" integer,
  "IdOrden" integer,
  "IdOpc" text,
  "IdPac" integer,
  "Fecha" timestamp with time zone,
  "Hora" timestamp with time zone,
  "Duracion" integer,
  "IdSitC" integer,
  "Texto" text,
  "Contacto" text,
  "NumPac" text,
  "Movil" text,
  "Nif" text,
  "Email" text,
  PRIMARY KEY ("IdMsg")
);

CREATE TABLE IF NOT EXISTS public."TDiagnosticos" (
  "IdPac" integer,
  "IdDiag" integer,
  "Descripcion" text,
  "FecIns" timestamp with time zone,
  "Comentario" text,
  "Fecha" timestamp with time zone,
  "IdUsu" integer,
  "Publico" text,
  "FecInactivo" timestamp with time zone,
  "IdTipoEspec" integer,
  "IdICD9" integer,
  "IdCentro" integer,
  "IdVisita" integer,
  "IdGestionTarifa" integer,
  "Guid_Tenant" uuid,
  "_version" integer,
  "_fechaReg" timestamp with time zone,
  "_idUserReg" integer,
  "_fechaModif" timestamp with time zone,
  "_idUserModif" integer,
  PRIMARY KEY ("IdDiag")
);

CREATE TABLE IF NOT EXISTS public."DCitasTto" (
  "IdCitasTto" integer,
  "IdUsu" integer,
  "IdOrden" integer,
  "IdentTM" integer,
  "IdTto" integer,
  "IdTipoOdg" integer,
  "Realizado" text,
  "_fechareg" timestamp with time zone,
  "IdCol" integer,
  "IdProced" integer,
  "IdRef" integer,
  "Notas" text,
  "Duracion" integer,
  "Guid_Tenant" uuid,
  PRIMARY KEY ("IdCitasTto")
);

CREATE TABLE IF NOT EXISTS public."SolicitudesFacturaEnvProte" (
  "Id" integer,
  "_version" integer,
  "_fechaReg" timestamp with time zone,
  "_idUserReg" integer,
  "_fechaModif" timestamp with time zone,
  "_idUserModif" integer,
  "Id_Centro" integer,
  "Id_Laboratorio" integer,
  "FechaDesde" timestamp with time zone,
  "FechaHasta" timestamp with time zone,
  "Importe" numeric,
  "Estado" integer,
  "FechaEnvSolicitudApi" timestamp with time zone,
  "FechaEnvEmailLaborario" timestamp with time zone,
  "FechaError" timestamp with time zone,
  "Resultado" text,
  "CodCentroCoste" text,
  "SecCentroCoste" integer,
  "CodSolicitud" text,
  "CodPedido" text,
  PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."TDiagnosticos_History" (
  "Id" integer,
  "IdPac" integer,
  "IdDiag" integer,
  "Descripcion" text,
  "FecIns" timestamp with time zone,
  "Comentario" text,
  "Fecha" timestamp with time zone,
  "IdUsu" integer,
  "Publico" text,
  "FecInactivo" timestamp with time zone,
  "IdTipoEspec" integer,
  "IdICD9" integer,
  "IdCentro" integer,
  "IdVisita" integer,
  "IdGestionTarifa" integer,
  "Guid_Tenant" uuid,
  "_version" integer,
  "_fechaReg" timestamp with time zone,
  "_idUserReg" integer,
  "_fechaModif" timestamp with time zone,
  "_idUserModif" integer,
  "DeletedBy" integer,
  "DeletedOn" timestamp with time zone,
  PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."ArqCajaTipoPago" (
  "IdArqCajaTipoPago" integer,
  "IdArqCaja" integer,
  "IdTipoPago" integer,
  "ImporteCalc" numeric,
  "ImporteArq" numeric,
  "Diferencia" numeric,
  "PctDif" numeric,
  "ImpAIngresar" numeric,
  "ImpSaldoFinal" numeric,
  "IdBancoIngr" integer,
  "IdCajaFuerte" integer,
  "IdMotivoIncidencia" integer,
  "NumDeposito" text,
  "ImpRedondeoSobrante" numeric,
  "ImpRedondeoFaltante" numeric,
  "ImpRedondeo" numeric,
  "Guid_Tenant" uuid,
  PRIMARY KEY ("IdArqCajaTipoPago")
);

CREATE TABLE IF NOT EXISTS public."EdDocs" (
  "IdDoc" integer,
  "IdGrupo" integer,
  "IdSubGrupo" integer,
  "FecCreado" timestamp with time zone,
  "FecModific" timestamp with time zone,
  "Titulo" text,
  "IdUsu" integer,
  "IdTipoEspec" integer,
  "Publico" text,
  "Firmado" timestamp with time zone,
  "FirmaIdUsu" integer,
  "IdentTM" integer,
  "IdCol" integer,
  "IdIdioma" integer,
  "IdCentro" integer,
  "Estado" integer,
  "CamposVariablesUsados" text,
  PRIMARY KEY ("IdDoc")
);

CREATE TABLE IF NOT EXISTS public."TDocsAdjuntos" (
  "IdPac" integer,
  "IdDoc" integer,
  "IdUsu" integer,
  "Descripcion" text,
  "Original" text,
  "Fecha" timestamp with time zone,
  "FechaIns" timestamp with time zone,
  "IdTipoEspec" integer,
  "Notas" text,
  "Publico" text,
  "IdentTM" integer,
  "Firmado" timestamp with time zone,
  "FirmaIdUsu" integer,
  "IdCentro" integer,
  "IdVisita" integer,
  PRIMARY KEY ("IdDoc")
);

CREATE TABLE IF NOT EXISTS public."CCDiagnosticos" (
  "Id" integer,
  "_version" integer,
  "_fechaReg" timestamp with time zone,
  "_idUserReg" integer,
  "_fechaModif" timestamp with time zone,
  "_idUserModif" integer,
  "IdDiagnostico" integer,
  "IdTarifa" integer,
  "IdCanasta" integer,
  "NivelRiesgo" integer,
  "IdColaborador" integer,
  "AcumuladoCopago" numeric,
  "AcumuladoComercial" numeric,
  "IdCCGrupo" integer,
  PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."DocsFirmados" (
  "IdDocFirma" integer,
  "FechaDoc" timestamp with time zone,
  "FechaIns" timestamp with time zone,
  "TipoDoc" integer,
  "TipoFirma" integer,
  "Descripcion" text,
  "Original" text,
  "Firmado" timestamp with time zone,
  "FirmaIdUsu" integer,
  "IdOrigen" integer,
  "IdPac" integer,
  "IdColFirma" integer,
  "Estado" integer,
  "FechaPublicado" timestamp with time zone,
  "NumRefPublicado" text,
  "Id_Pluggin" integer,
  "Guid_Tenant" uuid,
  "FirmadoColaborador" timestamp with time zone,
  PRIMARY KEY ("IdDocFirma")
);

CREATE TABLE IF NOT EXISTS public."NV_DetFactura" (
  "Id" integer,
  "No Empresa" text,
  "Tipo Documento" integer,
  "No documento" text,
  "No linea" integer,
  "Descripcion" text,
  "Cantidad" numeric,
  "Precio unitario" numeric,
  "Nombre medico" text,
  "No encuentro" text,
  "Familia" text,
  "Division" text,
  "Area" text,
  "Especialidad" text,
  "Zona" text,
  "Centro" text,
  "Medico" text,
  "Compañia" text,
  "Financiacion" text,
  "IVA" text,
  PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Pacientes_Conversaciones" (
  "Id" integer,
  "IdPac" integer,
  "Fecha" timestamp with time zone,
  "Medio" integer,
  "HabladoConDoctor" boolean,
  "HabladoConReferidor" boolean,
  "HabladoConPaciente" boolean,
  "HabladoConPadre" boolean,
  "HabladoConMadre" boolean,
  "HabladoConOtros" boolean,
  "Asunto" text,
  "Notas" text,
  "_version" integer,
  "_fechaReg" timestamp with time zone,
  "_idUserReg" integer,
  "_fechaModif" timestamp with time zone,
  "_idUserModif" integer,
  "TipoConversacion" integer,
  PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."TCentros" (
  "IdCentro" integer,
  "IdTipoCentro" integer,
  "Nombre" text,
  "NIF" text,
  "Direccion" text,
  "CP" text,
  "IdPoblacio" integer,
  "Tel1" text,
  "Tel2" text,
  "Fax" text,
  "Movil" text,
  "EMail" text,
  "Web" text,
  "Contacto1" text,
  "Contacto2" text,
  "Contacto3" text,
  "Observaciones" text,
  "TipoDocIdent" integer,
  PRIMARY KEY ("IdCentro")
);

CREATE TABLE IF NOT EXISTS public."TtosMedFases" (
  "IdTtosMedFase" integer,
  "IdTtosMed" integer,
  "IdTratamientoFase" integer,
  "NumFase" integer,
  "Estado" integer,
  "Fecha" timestamp with time zone,
  "Notas" text,
  "TpcFacturar" numeric,
  "_fechareg" timestamp with time zone,
  "_version" integer,
  "IdLiqComisionDet" integer,
  "IdCol" integer,
  "IdColAux" integer,
  "Guid_Tenant" uuid,
  PRIMARY KEY ("IdTtosMedFase")
);

CREATE TABLE IF NOT EXISTS public."DeudaPago" (
  "IdDeudaCli" integer,
  "IdPagoCli" integer,
  "Pagado" numeric,
  "FecPago" timestamp with time zone,
  "EditTtos" integer,
  "FecExpoCP" timestamp with time zone,
  "_fechareg" timestamp with time zone,
  "IdDeudaPago" integer,
  "IdDocAdminDeuda" integer,
  "SubTipoPago" integer,
  "IdLiqComisionDet" integer,
  "Guid_Tenant" uuid,
  "CId" text,
  PRIMARY KEY ("IdDeudaPago")
);

CREATE TABLE IF NOT EXISTS public."ProteFacturas" (
  "Id" integer,
  "IdCentro" integer,
  "IdProte" integer,
  "Fecha" timestamp with time zone,
  "Numero" text,
  "Importe" numeric,
  "IVA" numeric,
  "IdEstado" integer,
  "IdUserEstado" integer,
  "IdMotivoAceptacion" integer,
  "DescMotivoAceptacion" text,
  "_fechareg" timestamp with time zone,
  "_version" integer,
  "_iduser" integer,
  PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."ProveedsFactura" (
  "IdProveedFactura" integer,
  "IdCentro" integer,
  "IdProveed" integer,
  "Fecha" timestamp with time zone,
  "Numero" text,
  "Importe" numeric,
  "IVA" numeric,
  "IdEstado" integer,
  "IdUserEstado" integer,
  "IdMotivoAceptacion" integer,
  "DescMotivoAceptacion" text,
  "_fechareg" timestamp with time zone,
  "_version" integer,
  "_iduser" integer,
  PRIMARY KEY ("IdProveedFactura")
);

CREATE TABLE IF NOT EXISTS public."TtosMedImplantes" (
  "IdTtosMedImplante" integer,
  "IdTtosMed" integer,
  "FechaImplante" timestamp with time zone,
  "IdImplante" integer,
  "Fabricante" text,
  "DescripcionImplante" text,
  "MedidaImplante" text,
  "NumLote" text,
  "NumPieza" integer,
  "_fechareg" timestamp with time zone,
  "_usuario" integer,
  "_version" integer,
  "Hueso" boolean,
  "Membrana" boolean,
  "Guid_Tenant" uuid,
  PRIMARY KEY ("IdTtosMedImplante")
);

CREATE TABLE IF NOT EXISTS public."Sch_Resources_Centros_AOL" (
  "Id" integer,
  "Id_Resource" integer,
  "Id_Centro" integer,
  "AOAgdGUID" text,
  "AODescripcio" text,
  "AOFecPubDesde" timestamp with time zone,
  "AOFecPubHasta" timestamp with time zone,
  "Enabled" boolean,
  "_version" integer,
  "_fechaReg" timestamp with time zone,
  "_idUserReg" integer,
  "_fechaModif" timestamp with time zone,
  "_idUserModif" integer,
  "Guid_Tenant" uuid,
  PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."TForPago" (
  "IdForPago" integer,
  "Tipo" integer,
  "Descripcio" text,
  "Inactivo" timestamp with time zone,
  "_version" integer,
  "_fechaReg" timestamp with time zone,
  "_idUserReg" integer,
  "_fechaModif" timestamp with time zone,
  "_idUserModif" integer,
  "IdAgrupacionFormaPago" integer,
  "ModoFinanciacion" integer,
  "TPVVirtual" boolean,
  "TPVFisico" boolean,
  "Guid_Tenant" uuid,
  PRIMARY KEY ("IdForPago")
);

CREATE TABLE IF NOT EXISTS public."TalonariosFactura" (
  "Id" integer,
  "IdCentro" integer,
  "IdUser" integer,
  "IdEstado" integer,
  "TipoTalonario" integer,
  "TipoDocumento" integer,
  "RangoInicio" integer,
  "RangoFin" integer,
  "TalonActual" integer,
  "_fechaReg" timestamp with time zone,
  "_idUserReg" integer,
  "_fechaModif" timestamp with time zone,
  "_idUserModif" integer,
  "_version" integer,
  PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."DCitasGrp" (
  "IdDCitasGrp" integer,
  "IdUsu" integer,
  "IdOrden" integer,
  "IdPac" integer,
  "NumPac" text,
  "Texto" text,
  "IdCitasP" integer,
  "FechaPeriodIni" timestamp with time zone,
  "FechaPeriodFin" timestamp with time zone,
  "IdDCitasGrpGen" integer,
  PRIMARY KEY ("IdDCitasGrp")
);

CREATE TABLE IF NOT EXISTS public."DCitasLogSit" (
  "IdCitasLogSit" integer,
  "IdUsu" integer,
  "IdOrden" integer,
  "IdSitC" integer,
  "HorSitCita" timestamp with time zone,
  "HorFinSit" timestamp with time zone,
  "IdUserLog" integer,
  "IdMotivoAnulacion" integer,
  "MotivoAnulacion" text,
  "_fechaReg" timestamp with time zone,
  "IdOrigenSitCita" integer,
  PRIMARY KEY ("IdCitasLogSit")
);

CREATE TABLE IF NOT EXISTS public."DocsPublicados_CPS" (
  "Id" integer,
  "IdDoc" integer,
  "TipoDoc" integer,
  "idSocio" text,
  "idCentro" text,
  "tipoArchivo" integer,
  "estado" text,
  "idProveedor" text,
  "ruta" text,
  "usuarioGesden" text,
  "Origen" text,
  "iplocal" text,
  "codRespuesta" integer,
  "descRespuesta" text,
  "idInformacionMedica" text,
  "_fechareg" timestamp with time zone,
  PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."PasarelaPago" (
  "Id" integer,
  "IdPac" integer,
  "IdConector" integer,
  "IdNumTransaccion" integer,
  "IdEmisor" integer,
  "NumeroUnicoTransaccionOriginal" text,
  "Estado" integer,
  "_version" integer,
  "_fechaReg" timestamp with time zone,
  "_idUserReg" integer,
  "_fechaModif" timestamp with time zone,
  "_idUserModif" integer,
  PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."RecetasDet" (
  "IdPac" integer,
  "IdReceta" integer,
  "IdTrat" integer,
  "DescFarmaco" text,
  "DispPrev" timestamp with time zone,
  "Duracion" text,
  "Envases" integer,
  "OrdenDisp" integer,
  "Pauta" text,
  "Posologia" text,
  "Unidades" text,
  "IdRecetaDet" integer,
  "Guid_Tenant" uuid,
  PRIMARY KEY ("IdRecetaDet")
);

CREATE TABLE IF NOT EXISTS public."Centros_Tarifas" (
  "IdCentroTarifa" integer,
  "IdCentro" integer,
  "IdTarifa" integer,
  "Inactivo" timestamp with time zone,
  "Desde" timestamp with time zone,
  "Hasta" timestamp with time zone,
  "_fechareg" timestamp with time zone,
  "_version" integer,
  "Guid_Tenant" uuid,
  "_idUserReg" integer,
  "_fechaModif" timestamp with time zone,
  "_idUserModif" integer,
  PRIMARY KEY ("IdCentroTarifa")
);

CREATE TABLE IF NOT EXISTS public."GDPRConsentimientos" (
  "Id" integer,
  "_version" integer,
  "_fechaReg" timestamp with time zone,
  "_idUserReg" integer,
  "_fechaModif" timestamp with time zone,
  "_idUserModif" integer,
  "Descripcion" text,
  "Personalizable" boolean,
  "Orden" integer,
  "DescCorta" text,
  "Grupo" text,
  "Detalles" text,
  "Ejemplo" text,
  "CodExt" text,
  "Guid_Tenant" uuid,
  PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."GDPRConsentimientos_Texts" (
  "Id" integer,
  "_version" integer,
  "_fechaReg" timestamp with time zone,
  "_idUserReg" integer,
  "_fechaModif" timestamp with time zone,
  "_idUserModif" integer,
  "Id_GDPRConsentimientos" integer,
  "Id_Idioma" integer,
  "DescCorta" text,
  "Grupo" text,
  "Detalles" text,
  "Ejemplo" text,
  PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."NV_CabFactura" (
  "Id" integer,
  "No Empresa" text,
  "Tipo Documento" integer,
  "No" text,
  "Venta a No Cliente" text,
  "Fecha Registro" timestamp with time zone,
  "Texto Registro" text,
  "No Historial clinico" text,
  "Usuario" text,
  "Nombre fiscal" text,
  "provincia" text,
  "NIF_Permiso residencia" text,
  "No serie" text,
  "Liquidado Tipo Documento" integer,
  "Liquidado Numero Documento" text,
  PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."Digit_PdfPresupuestos" (
  "Id" integer,
  "IdPresupuesto" integer,
  "IdPaciente" integer,
  "IdCentro" integer,
  "FileName" text,
  "VersionPresupuesto" integer,
  "Status" integer,
  "_version" integer,
  "_fechareg" timestamp with time zone,
  "_fechaModif" timestamp with time zone,
  PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."PacPerio" (
  "IdPac" integer,
  "IdExplPer" integer,
  "Fecha" timestamp with time zone,
  "NotasSup" text,
  "NotasInf" text,
  "Id" integer,
  "_version" integer,
  "_fechaReg" timestamp with time zone,
  "_idUserReg" integer,
  "_fechaModif" timestamp with time zone,
  "_idUserModif" integer,
  "Guid_Tenant" uuid,
  PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."TUsers_Conectores" (
  "Id" integer,
  "_version" integer,
  "_fechaReg" timestamp with time zone,
  "_idUserReg" integer,
  "_fechaModif" timestamp with time zone,
  "_idUserModif" integer,
  "Id_User" integer,
  "Id_Conector" integer,
  "IdUserConector" text,
  "Comodin" text,
  "Inactivo" timestamp with time zone,
  PRIMARY KEY ("Id")
);

CREATE TABLE IF NOT EXISTS public."TtosMedSes" (
  "IdPac" integer,
  "NumTto" integer,
  "NumFase" integer,
  "IdSesion" integer,
  "Notas" text,
  "StaTto" integer,
  "Fecha" timestamp with time zone,
  "IdCol" integer,
  "IdUser" integer,
  "_fechareg" timestamp with time zone,
  "IdentTM" integer,
  PRIMARY KEY ("IdPac", "NumTto", "NumFase", "IdSesion")
);

CREATE TABLE IF NOT EXISTS public."AGDNOTAS" (
  "IdNota" integer,
  "Nota" text,
  "Fecha" integer,
  "IdUsu" integer,
  "IdCentro" integer,
  PRIMARY KEY ("IdNota")
);

CREATE TABLE IF NOT EXISTS public."PRESU" (
  "IdPac" integer,
  "NumSerie" integer,
  "NumPre" integer,
  "Titulo" text,
  "Notas" text,
  "Direccion" text,
  "IdPoblacio" integer,
  "CP" text,
  "Tel1" text,
  "Tel2" text,
  "TelMovil" text,
  "Fax" text,
  "Email" text,
  "Web" text,
  "FecPresup" timestamp with time zone,
  "FecAcepta" timestamp with time zone,
  "IdCol" integer,
  "Emisor" integer,
  "Ident" integer,
  "FecRechaz" timestamp with time zone,
  "ObsRechaz" text,
  "IdUserElabora" integer,
  "IdCentro" integer,
  "IdUserPresentacion" integer,
  "UniqueID" integer,
  "IdPresuOrigen" integer,
  "IdTipoPresupuesto" integer,
  "Estado" integer,
  "AceptadoFueraValidez" integer,
  "Financiacion" integer,
  "_fechareg" timestamp with time zone,
  "_version" integer,
  "RechazadoPorAlternativa" boolean,
  "AlternativaDe" integer,
  "EsAlternativa" integer,
  "IdCanastaDiagnostico" integer,
  "Id_UserDesbloqueo" integer,
  "FechaDesbloqueo" timestamp with time zone,
  "Id_UserResponsable" integer,
  "ContratoFinanciacion" text,
  "Id_MotivoRechaz" integer,
  "Id_UserRechaz" integer,
  "Id_PresuOriginal" integer,
  "FechaEntregaDigitalmente" timestamp with time zone,
  "FechaRecibidoCliente" timestamp with time zone,
  "RecibidoDigitalmente" boolean,
  "Guid_Tenant" uuid,
  "Serie" text,
  "NumSeriePresu" integer,
  "Hash" text,
  "HashControl" integer,
  "CodigoATCUD" text,
  "CodigoQR" text,
  "FechaAceptadoDigitalmente" timestamp with time zone,
  PRIMARY KEY ("IdPac", "NumPre")
);

CREATE TABLE IF NOT EXISTS public."PRESUTTO" (
  "IdPac" integer,
  "NumSerie" integer,
  "NumPre" integer,
  "LinPre" integer,
  "IdTto" integer,
  "ZonasBoca" integer,
  "PiezasAdu" numeric,
  "PiezasLec" numeric,
  "PiezasNum" numeric,
  "ZonasPieza" numeric,
  "DespX" integer,
  "DespY" integer,
  "Rotacion" integer,
  "StaTto" integer,
  "FecIni" timestamp with time zone,
  "FecFin" timestamp with time zone,
  "IdCol" integer,
  "IdCli" integer,
  "Unidades" integer,
  "ImportePre" numeric,
  "Dto" integer,
  "Notas" text,
  "IdTipoOdg" integer,
  "Tiempo" integer,
  "FecAcepta" timestamp with time zone,
  "BaseImponible" numeric,
  "IdTipoIVA" integer,
  "TpcIVA" numeric,
  "ImporteIVA" numeric,
  "ImporteUni" numeric,
  "IdColAux" integer,
  "ImporteDto" numeric,
  "Ident" integer,
  "Orden" integer,
  "IdTratamiento" integer,
  "_version" integer,
  "IdTtoMedOrig" integer,
  "Cuadrantes" numeric,
  "Arcadas" numeric,
  "Id_Presu" integer,
  "Guid_Tenant" uuid,
  PRIMARY KEY ("Ident")
);

