-- 🚀 SCRIPT OFICIAL DE MIGRACIÓN SUPABASE (Nomenclatura GELITE) 🚀
-- ==========================================
-- 1. LIMPIEZA DE TABLAS ANTERIORES (Opcional pero recomendado para pruebas)
-- ==========================================
-- DROP TABLE IF EXISTS "ATMT_Plantillas" CASCADE;
-- DROP TABLE IF EXISTS "ATMT_Coms" CASCADE;
-- DROP TABLE IF EXISTS "Pacientes_Conversaciones" CASCADE;
-- DROP TABLE IF EXISTS "StckMov" CASCADE;
-- DROP TABLE IF EXISTS "TArticulo" CASCADE;
-- DROP TABLE IF EXISTS "PagoCli" CASCADE;
-- DROP TABLE IF EXISTS "BancoMov" CASCADE;
-- DROP TABLE IF EXISTS "NV_CabFactura" CASCADE;
-- DROP TABLE IF EXISTS "PresuTto" CASCADE;
-- DROP TABLE IF EXISTS "Presu" CASCADE;
-- DROP TABLE IF EXISTS "TBloqueos" CASCADE;
-- DROP TABLE IF EXISTS "DCitas" CASCADE;
-- DROP TABLE IF EXISTS "TDocsAdjuntos" CASCADE;
-- DROP TABLE IF EXISTS "AgdNotas" CASCADE;
-- DROP TABLE IF EXISTS "TDiagnosticos" CASCADE;
-- DROP TABLE IF EXISTS "Tratamientos" CASCADE;
-- DROP TABLE IF EXISTS "AlertPac" CASCADE;
-- DROP TABLE IF EXISTS "Clientes" CASCADE;
-- DROP TABLE IF EXISTS "pacientes" CASCADE; -- Tabla vieja
-- DROP TABLE IF EXISTS "citas" CASCADE; -- Tabla vieja
-- ==========================================
-- 2. SECUENCIAS O EXTENSIONES
-- ==========================================
-- Activa la extensión para generar UUIDs si no está activa
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
-- ==========================================
-- 3. CREACIÓN DE TABLAS (CORE)
-- ==========================================
-- Tabla Clientes (antiguamente 'pacientes')
CREATE TABLE IF NOT EXISTS "Clientes" (
    "IdCli" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "NumPac" TEXT,
    "Nombre" TEXT,
    "Apellidos" TEXT,
    "NIF" TEXT,
    "TelMovil" TEXT,
    "Tel1" TEXT,
    "Email" TEXT,
    "FecNacim" DATE,
    "Direccion" TEXT,
    "CP" TEXT,
    "Notas" TEXT,
    "FecAlta" TIMESTAMPTZ DEFAULT now(),
    "_fechareg" TIMESTAMPTZ DEFAULT now(),
    "updated_at" TIMESTAMPTZ DEFAULT now()
);
-- Tabla AlertPac (Alertas médicas)
CREATE TABLE IF NOT EXISTS "AlertPac" (
    "Id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "IdPac" INT REFERENCES "Clientes"("IdCli") ON DELETE CASCADE,
    "Texto" TEXT NOT NULL,
    "Marcado" BOOLEAN DEFAULT true,
    "_fechaReg" TIMESTAMPTZ DEFAULT now()
);
-- Tabla Tratamientos (Odontograma y Actos)
CREATE TABLE IF NOT EXISTS "Tratamientos" (
    "IdTratamiento" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "IdPac" INT REFERENCES "Clientes"("IdCli") ON DELETE CASCADE,
    "Piezas" TEXT,
    "DescripMed" TEXT,
    "DescripPac" TEXT,
    "_fechaReg" TIMESTAMPTZ DEFAULT now(),
    "updated_at" TIMESTAMPTZ DEFAULT now()
);
-- Tabla TDiagnosticos y AgdNotas (Evolutivos SOAP)
CREATE TABLE IF NOT EXISTS "TDiagnosticos" (
    "IdDiag" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "IdPac" INT REFERENCES "Clientes"("IdCli") ON DELETE CASCADE,
    "Fecha" DATE,
    "Comentario" TEXT,
    "IdUsu" UUID,
    -- Este puede seguir siendo UUID si referencia a auth.users
    "FecIns" TIMESTAMPTZ DEFAULT now(),
    "updated_at" TIMESTAMPTZ DEFAULT now()
);
CREATE TABLE IF NOT EXISTS "AgdNotas" (
    "IdNota" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "IdPac" INT REFERENCES "Clientes"("IdCli") ON DELETE CASCADE,
    "Fecha" DATE,
    "Nota" TEXT,
    "IdUsu" UUID,
    "FecIns" TIMESTAMPTZ DEFAULT now(),
    "updated_at" TIMESTAMPTZ DEFAULT now()
);
-- Tabla TDocsAdjuntos (Documentos adjuntos)
CREATE TABLE IF NOT EXISTS "TDocsAdjuntos" (
    "IdDoc" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "IdPac" INT REFERENCES "Clientes"("IdCli") ON DELETE CASCADE,
    "Nombre" TEXT,
    "URL" TEXT,
    "FecIns" DATE DEFAULT CURRENT_DATE
);
-- ==========================================
-- 4. CREACIÓN DE TABLAS (AGENDA)
-- ==========================================
-- Tabla DCitas
CREATE TABLE IF NOT EXISTS "DCitas" (
    "IdCita" BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "IdPac" INT REFERENCES "Clientes"("IdCli") ON DELETE CASCADE,
    "NUMPAC" TEXT,
    "IdCol" INT,
    "IdBox" TEXT,
    -- Gabinete (G1, G2...)
    "Fecha" DATE,
    "HorConsul" TIME,
    "Duracion" INT,
    "Texto" TEXT,
    "NOTAS" TEXT,
    "IdSitC" INT,
    -- Estado (0: planificada, etc)
    "Confirmada" BOOLEAN DEFAULT false,
    "Aceptada" BOOLEAN DEFAULT false,
    "FecAlta" TIMESTAMPTZ DEFAULT now(),
    "updated_at" TIMESTAMPTZ DEFAULT now()
);
-- Tabla TBloqueos
CREATE TABLE IF NOT EXISTS "TBloqueos" (
    "IdBloqueo" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "FechaDesde" TIMESTAMPTZ,
    "FechaHasta" TIMESTAMPTZ,
    "Motivo" TEXT,
    "IdBox" TEXT
);
-- ==========================================
-- 5. CREACIÓN DE TABLAS (FINANCIERO)
-- ==========================================
CREATE TABLE IF NOT EXISTS "Presu" (
    "NumPre" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "IdPac" INT REFERENCES "Clientes"("IdCli") ON DELETE CASCADE,
    "FecPresup" DATE,
    "Estado" TEXT,
    "IdCol" INT,
    "Notas" TEXT
);
CREATE TABLE IF NOT EXISTS "PresuTto" (
    "Id" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "NumPre" INT REFERENCES "Presu"("NumPre") ON DELETE CASCADE,
    "IdTto" INT REFERENCES "Tratamientos"("IdTratamiento"),
    "Importe" NUMERIC,
    "Unidades" INT
);
CREATE TABLE IF NOT EXISTS "NV_CabFactura" (
    "Id" BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "No" TEXT,
    -- Numero de la factura
    "IdPac" INT REFERENCES "Clientes"("IdCli") ON DELETE CASCADE,
    "No Empresa" TEXT,
    "Nombre fiscal" TEXT,
    "NIF_Permiso residencia" TEXT,
    "Fecha Registro" DATE,
    "Total" NUMERIC,
    "_fechareg" TIMESTAMPTZ DEFAULT now()
);
CREATE TABLE IF NOT EXISTS "BancoMov" (
    "Apunte" BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "IdBanco" INT,
    "Concepto" TEXT,
    "Importe" NUMERIC,
    "Tipo" TEXT,
    "Fecha" DATE DEFAULT CURRENT_DATE
);
CREATE TABLE IF NOT EXISTS "PagoCli" (
    "IdPagoCli" BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "IdCli" INT REFERENCES "Clientes"("IdCli") ON DELETE CASCADE,
    "FecPago" DATE DEFAULT CURRENT_DATE,
    "Importe" NUMERIC,
    "IdBanco" INT,
    "IdentTM" TEXT,
    "Nota" TEXT
);
-- ==========================================
-- 6. CREACIÓN DE TABLAS (INVENTARIO)
-- ==========================================
CREATE TABLE IF NOT EXISTS "TArticulo" (
    "IdArticulo" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "Nombre" TEXT NOT NULL,
    "Codigo" TEXT,
    "SKU" TEXT,
    "StockFisico" INT DEFAULT 0,
    "PrecioCompra" NUMERIC
);
CREATE TABLE IF NOT EXISTS "StckMov" (
    "IdMov" BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "IdArticulo" INT REFERENCES "TArticulo"("IdArticulo") ON DELETE CASCADE,
    "Lote" TEXT,
    "FecCaducidad" DATE,
    "Cantidad" INT,
    "IdPac" INT REFERENCES "Clientes"("IdCli"),
    "IdCita" BIGINT REFERENCES "DCitas"("IdCita")
);
-- ==========================================
-- 7. CREACIÓN DE TABLAS (AUTOMATIZACIONES Y CHAT)
-- ==========================================
CREATE TABLE IF NOT EXISTS "Pacientes_Conversaciones" (
    "IdConversacion" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "IdPac" INT REFERENCES "Clientes"("IdCli"),
    "Telefono" TEXT,
    "UltimaActividad" TIMESTAMPTZ DEFAULT now()
);
CREATE TABLE IF NOT EXISTS "ATMT_Coms" (
    "Id" BIGINT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "IdPac" INT REFERENCES "Clientes"("IdCli"),
    "DatosPlantilla" TEXT,
    "Contenido" TEXT,
    "Telefono" TEXT,
    "OrigenIncidencia" TEXT,
    "FechaEnvio" TIMESTAMPTZ DEFAULT now()
);
CREATE TABLE IF NOT EXISTS "ATMT_Plantillas" (
    "IdPlantilla" INT PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    "Descripcion" TEXT,
    "PlantillaSMS" TEXT,
    "Inactiva" BOOLEAN DEFAULT false
);
-- ==========================================
-- 8. TRIGGERS (Actualización de fechas automáticas)
-- ==========================================
CREATE OR REPLACE FUNCTION update_updated_at_column() RETURNS TRIGGER AS $$ BEGIN NEW.updated_at = now();
RETURN NEW;
END;
$$ language 'plpgsql';
CREATE TRIGGER update_clientes_updated_at BEFORE
UPDATE ON "Clientes" FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_tratamientos_updated_at BEFORE
UPDATE ON "Tratamientos" FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_tdiagnosticos_updated_at BEFORE
UPDATE ON "TDiagnosticos" FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_agdnotas_updated_at BEFORE
UPDATE ON "AgdNotas" FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
CREATE TRIGGER update_dcitas_updated_at BEFORE
UPDATE ON "DCitas" FOR EACH ROW EXECUTE PROCEDURE update_updated_at_column();
-- ==========================================
-- 9. HABILITAR SEGURIDAD POR NIVEL DE FILAS (RLS)
-- ==========================================
ALTER TABLE "Clientes" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AlertPac" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Tratamientos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TDiagnosticos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "AgdNotas" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TDocsAdjuntos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "DCitas" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TBloqueos" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Presu" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PresuTto" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "NV_CabFactura" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "BancoMov" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "PagoCli" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "TArticulo" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "StckMov" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "Pacientes_Conversaciones" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ATMT_Coms" ENABLE ROW LEVEL SECURITY;
ALTER TABLE "ATMT_Plantillas" ENABLE ROW LEVEL SECURITY;
-- ==========================================
-- 10. POLÍTICAS DE ACCESO MÁS PERMISIVAS (Temporal para Desarrollo / API local)
-- ==========================================
-- Para permitir interactuar con Supabase en la fase actual de desarrollo
CREATE POLICY "Activar permisos totales desarrollo" ON "Clientes" FOR ALL USING (true);
CREATE POLICY "Activar permisos totales desarrollo" ON "DCitas" FOR ALL USING (true);
CREATE POLICY "Activar permisos totales desarrollo" ON "Tratamientos" FOR ALL USING (true);
CREATE POLICY "Activar permisos totales desarrollo" ON "TDiagnosticos" FOR ALL USING (true);
CREATE POLICY "Activar permisos totales desarrollo" ON "AgdNotas" FOR ALL USING (true);
CREATE POLICY "Activar permisos totales desarrollo" ON "AlertPac" FOR ALL USING (true);
CREATE POLICY "Activar permisos totales desarrollo" ON "Presu" FOR ALL USING (true);
CREATE POLICY "Activar permisos totales desarrollo" ON "PresuTto" FOR ALL USING (true);
CREATE POLICY "Activar permisos totales desarrollo" ON "NV_CabFactura" FOR ALL USING (true);
CREATE POLICY "Activar permisos totales desarrollo" ON "PagoCli" FOR ALL USING (true);
CREATE POLICY "Activar permisos totales desarrollo" ON "BancoMov" FOR ALL USING (true);
CREATE POLICY "Activar permisos totales desarrollo" ON "TArticulo" FOR ALL USING (true);
CREATE POLICY "Activar permisos totales desarrollo" ON "StckMov" FOR ALL USING (true);
CREATE POLICY "Activar permisos totales desarrollo" ON "ATMT_Coms" FOR ALL USING (true);
CREATE POLICY "Activar permisos totales desarrollo" ON "TDocsAdjuntos" FOR ALL USING (true);
CREATE POLICY "Activar permisos totales desarrollo" ON "TBloqueos" FOR ALL USING (true);
CREATE POLICY "Activar permisos totales desarrollo" ON "ATMT_Plantillas" FOR ALL USING (true);
CREATE POLICY "Activar permisos totales desarrollo" ON "Pacientes_Conversaciones" FOR ALL USING (true);