CREATE TABLE IF NOT EXISTS public."AGDNOTAS" (
  "IdNota" integer,
  "Nota" text,
  "Fecha" integer,
  "IdUsu" integer,
  "IdCentro" integer,
  PRIMARY KEY ("IdNota")
);

CREATE TABLE IF NOT EXISTS public."PRESU" (
  "IdPac" integer,
  "NumSerie" integer,
  "NumPre" integer,
  "Titulo" text,
  "Notas" text,
  "Direccion" text,
  "IdPoblacio" integer,
  "CP" text,
  "Tel1" text,
  "Tel2" text,
  "TelMovil" text,
  "Fax" text,
  "Email" text,
  "Web" text,
  "FecPresup" timestamp with time zone,
  "FecAcepta" timestamp with time zone,
  "IdCol" integer,
  "Emisor" integer,
  "Ident" integer,
  "FecRechaz" timestamp with time zone,
  "ObsRechaz" text,
  "IdUserElabora" integer,
  "IdCentro" integer,
  "IdUserPresentacion" integer,
  "UniqueID" integer,
  "IdPresuOrigen" integer,
  "IdTipoPresupuesto" integer,
  "Estado" integer,
  "AceptadoFueraValidez" integer,
  "Financiacion" integer,
  "_fechareg" timestamp with time zone,
  "_version" integer,
  "RechazadoPorAlternativa" boolean,
  "AlternativaDe" integer,
  "EsAlternativa" integer,
  "IdCanastaDiagnostico" integer,
  "Id_UserDesbloqueo" integer,
  "FechaDesbloqueo" timestamp with time zone,
  "Id_UserResponsable" integer,
  "ContratoFinanciacion" text,
  "Id_MotivoRechaz" integer,
  "Id_UserRechaz" integer,
  "Id_PresuOriginal" integer,
  "FechaEntregaDigitalmente" timestamp with time zone,
  "FechaRecibidoCliente" timestamp with time zone,
  "RecibidoDigitalmente" boolean,
  "Guid_Tenant" uuid,
  "Serie" text,
  "NumSeriePresu" integer,
  "Hash" text,
  "HashControl" integer,
  "CodigoATCUD" text,
  "CodigoQR" text,
  "FechaAceptadoDigitalmente" timestamp with time zone,
  PRIMARY KEY ("IdPac", "NumPre")
);

CREATE TABLE IF NOT EXISTS public."PRESUTTO" (
  "IdPac" integer,
  "NumSerie" integer,
  "NumPre" integer,
  "LinPre" integer,
  "IdTto" integer,
  "ZonasBoca" integer,
  "PiezasAdu" numeric,
  "PiezasLec" numeric,
  "PiezasNum" numeric,
  "ZonasPieza" numeric,
  "DespX" integer,
  "DespY" integer,
  "Rotacion" integer,
  "StaTto" integer,
  "FecIni" timestamp with time zone,
  "FecFin" timestamp with time zone,
  "IdCol" integer,
  "IdCli" integer,
  "Unidades" integer,
  "ImportePre" numeric,
  "Dto" integer,
  "Notas" text,
  "IdTipoOdg" integer,
  "Tiempo" integer,
  "FecAcepta" timestamp with time zone,
  "BaseImponible" numeric,
  "IdTipoIVA" integer,
  "TpcIVA" numeric,
  "ImporteIVA" numeric,
  "ImporteUni" numeric,
  "IdColAux" integer,
  "ImporteDto" numeric,
  "Ident" integer,
  "Orden" integer,
  "IdTratamiento" integer,
  "_version" integer,
  "IdTtoMedOrig" integer,
  "Cuadrantes" numeric,
  "Arcadas" numeric,
  "Id_Presu" integer,
  "Guid_Tenant" uuid,
  PRIMARY KEY ("Ident")
);

